env:
  commonjs: true
  es2021: true
  node: true
  jest: true
extends:
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - airbnb-base
  - plugin:import/warnings
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/no-unresolved: [2, {commonjs: true, amd: true}]
settings:
  import/resolver:
    typescript: {}
