server:
  port: 10000
  timeout: 60000
  ssl:
    port: 10001
    key: ./server.key
    cert: ./server.crt
  public:
    path: public
    mount: /
  proxy:
    host: localhost
    port: 10002
    prefix: /api

  # logs
  log:
    infoFile: log/info.log
